source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PickerView_Example' do
  pod "PickerView", :path => "../"
end

target 'PickerView_Tests' do
  pod "PickerView", :path => "../"

  
end
