source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FAPickerView_Example', :exclusive => true do
  pod "FAPickerView", :path => "../"
end

target 'FAPickerView_Tests', :exclusive => true do
  pod "FAPickerView", :path => "../"

  
end
